# Generated by Django 5.1.3 on 2025-12-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('text', models.TextField(blank=True, default='')),
                ('mood', models.CharField(choices=[('great', '좋음'), ('good', '괜찮음'), ('meh', '그럭저럭'), ('bad', '힘듦'), ('awful', '매우 힘듦')], default='meh', max_length=10)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
